import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        shad:"#7E33E0",
        btn:"#0057FF",
        para:"#F1F1F1",
        sec:"#f7f7f7",
        li:"#FB2E86",
        border:"#E7E6EF",
        bg:"#FB2E86",
        promo:"#F2F0FF",
        off:"#00C1FE",
        chair:"#F6F7FB",
        pic:"#05E6B7",
        pic1:"#2F1AC4",
        latest:"#151875",
        blur:"#1A0B5B4D",
        green:"#08D15F",
        bluegradient:"#1389FF",
        rec:"#F1F0FF",
        back:"#F5E1FC",
        p:"#ACABC3",
        cir:"#F52B70",
        dot:"#2B2BF5",
        dot1:"#2BF5CC",
        pic2:"#F5F6F8",
        textblur:"#1518754D",
        new:"#FFF6FB",
        shade:"#EEEFFB",
        chairs:"#F5F6F8",
        text:"#7569B2",
        blr:"#B8B8DC",
        texts:"#72718F",
        bgs:"#EEEFFB",
        tex:"#8A8FB9",
        backs:"#F6F5FF",
        backss:"#101750",
        col:"#9096B2",
        textss:"#151875",
        textsss:"#5625DF",
        bgsS:"#37DAF3",
        subT:"#8A8FB9",
        bor:"#E7E6EF",
        orang:"#DE9034",
        yello:"#FFC416",
        textssss:"#B2B2B2",
        bgss:"#FFE7F9",
        bgsss:"#FFECE2",
        texte:"#1518751A"
        
      },
    },
  },
  plugins: [],
} satisfies Config;
